INSERT INTO users (first_name, last_name, password_hash) VALUES('Morten', 'Kose', '$2b$10$f7rEDhLXPc9n2q1vrFT9Su58CXB2mT696eGCTI2s1shNCp7j.xFZy');
INSERT INTO users (first_name, last_name, password_hash) VALUES('John', 'Doe', '$2b$10$4iAgLL6sr6SVq5g5kV3x5O8o7.z.Q4bI/npMwggUWRZ/DrtEFsQgu');
INSERT INTO users (first_name, last_name, password_hash) VALUES('Jane', 'Doe', '$2b$10$rDyk005VAg8okjiD5aD1HukeVaLybSzVBvz6nC3k3hJiFom0nvcu.');
INSERT INTO products (name, price , category) VALUES('Product 1', 25.00, 'cat1');
INSERT INTO products (name, price , category) VALUES('Product 2', 25.00, 'cat2');
INSERT INTO products (name, price , category) VALUES('Product 3', 5.00, 'cat1');
INSERT INTO products (name, price , category) VALUES('Product 4', 15.00, 'cat3');
INSERT INTO products (name, price , category) VALUES('Product 5', 2.00, 'cat4');
INSERT INTO products (name, price , category) VALUES('Product 6', 250.00, 'cat1');
INSERT INTO products (name, price , category) VALUES('Product 7', 254.00, 'cat4');
INSERT INTO products (name, price , category) VALUES('Product 8', 45.00, 'cat4');
INSERT INTO products (name, price , category) VALUES('Product 9', 22.00, 'cat3');
INSERT INTO products (name, price , category) VALUES('Product 10', 18.00, 'cat3');
INSERT INTO orders (user_id, status) VALUES(1, 'active');
INSERT INTO orders (user_id, status) VALUES(2, 'complete');
INSERT INTO orders (user_id, status) VALUES(3, 'active');
INSERT INTO orders (user_id, status) VALUES(1, 'complete');
INSERT INTO orders (user_id, status) VALUES(1, 'complete');
INSERT INTO products_in_order (order_id, product_id, quantity) VALUES(1, 5, 4);
INSERT INTO products_in_order (order_id, product_id, quantity) VALUES(1, 2, 2);
INSERT INTO products_in_order (order_id, product_id, quantity) VALUES(1, 4, 4);
INSERT INTO products_in_order (order_id, product_id, quantity) VALUES(2, 8, 12);
INSERT INTO products_in_order (order_id, product_id, quantity) VALUES(2, 5, 10);
INSERT INTO products_in_order (order_id, product_id, quantity) VALUES(2, 9, 1);
INSERT INTO products_in_order (order_id, product_id, quantity) VALUES(2, 7, 15);
INSERT INTO products_in_order (order_id, product_id, quantity) VALUES(3, 5, 6);
INSERT INTO products_in_order (order_id, product_id, quantity) VALUES(3, 7, 2);
INSERT INTO products_in_order (order_id, product_id, quantity) VALUES(3, 1, 3);
INSERT INTO products_in_order (order_id, product_id, quantity) VALUES(3, 3, 5);
INSERT INTO products_in_order (order_id, product_id, quantity) VALUES(4, 7, 1);
INSERT INTO products_in_order (order_id, product_id, quantity) VALUES(4, 8, 2);
INSERT INTO products_in_order (order_id, product_id, quantity) VALUES(4, 2, 1);
INSERT INTO products_in_order (order_id, product_id, quantity) VALUES(4, 10, 5);
INSERT INTO products_in_order (order_id, product_id, quantity) VALUES(5, 4, 2);
INSERT INTO products_in_order (order_id, product_id, quantity) VALUES(5, 7, 2);
INSERT INTO products_in_order (order_id, product_id, quantity) VALUES(5, 1, 2);
INSERT INTO products_in_order (order_id, product_id, quantity) VALUES(5, 6, 1);